### ISSUE TITLE
Add again the Airing, Airing Today, and Returning overlays to the returning-soon-overlay YML

### ISSUE THREAD

**Issue by bartolomesoriano** [InsertDisc/pattrmm#2]
In the previous incarnation of the script, the generated YML included overlays for Airing, Airing Today, and Returning shows.  Please add these to this version of the script, even if they are optional.

**Comment by InsertDisc** [comment]
There are now new options in the settings.yml to utilize the other overlays. Delete existing settings.yml if those options are not present, make sure to update the main script file, and run again.
