### ISSUE TITLE
Set custom font path

### ISSUE THREAD

**Issue by Dragonsys** [InsertDisc/pattrmm#52]
Is there a way to set the font path? I don't keep my fonts in /config/fonts, but I don't see a way to change this in the settings for pattrmm.

**Comment by itsFelixH** [comment]
The overlay template file will only be generated once. You can manually edit the font path there. PATTRMM will only check if the file exists and the use it.

But its a good idea to give an option beforehand. I will add a PR.

**Comment by Dragonsys** [comment]
Thank you

**Comment by Dragonsys** [comment]
I don't see a way to set these in the templates or the preferences 

visible_home: true
visible_shared: true

can they be added? Right now I have to edit the output yml files after every run to make sure the collections don't show up on the home page for all users. Or am I just missing it somewhere?

**Comment by InsertDisc** [comment]
This has been merged.
