### ISSUE TITLE
Script fails trying to get the library section id

### ISSUE THREAD

**Issue by bartolomesoriano** [InsertDisc/pattrmm#7]
While trying to get the library section id, the script fails with the following error:

"Traceback (most recent call last):
  File "E:\plex-meta-manager\config\scripts\pattrmm.py", line 699, in <module>
    plexCall = vars.plexApi('url') + '/library/sections/' + vars.plexGet(library) + '/all'
                                                            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\plex-meta-manager\config\scripts\vars.py", line 347, in plexGet
    return key
           ^^^
UnboundLocalError: cannot access local variable 'key' where it is not associated with a value"

@InsertDisc , from your comment on Discord this is happening for libraries that have spaces in the name.  In my case, the library does have a space in the name: "TV Shows".

**Comment by halfloaf123** [comment]
having the exact same issue

**Comment by InsertDisc** [comment]
This should be resolved now.
Will close once confirmed.

**Comment by InsertDisc** [comment]
Issue has been confirmed fixed.
